server:
  undertow:
  # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
  # 默认值是IO线程数*8,推荐 32 * nCPU
  #threads:
  #  worker: 128
  # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接
  # 默认设置每个CPU核心一个线程,推荐 4 * n CPU
  #  io: 16

spring:
  datasource:
    url: jdbc:mysql://10.3.69.41:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false
    username: root
    password: Abc#123456
  boot:
    admin:
      client:
        url: http://localhost:8080